# Generated by Django 5.2.3 on 2026-06-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriPengaduan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusLaporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Masyarakat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nik", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("alamat", models.TextField()),
                ("no_hp", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masyarakat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pengaduan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("isi_laporan", models.TextField()),
                (
                    "foto_bukti",
                    models.ImageField(blank=True, null=True, upload_to="pengaduan/"),
                ),
                ("hasil_klasifikasi", models.CharField(blank=True, max_length=100)),
                ("tanggal_pengaduan", models.DateTimeField(auto_now_add=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pengaduan.kategoripengaduan",
                    ),
                ),
                (
                    "masyarakat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pengaduan",
                        to="pengaduan.masyarakat",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pengaduan.statuslaporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Petugas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("jabatan", models.CharField(max_length=100)),
                ("no_hp", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petugas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiwayatStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("tanggal_update", models.DateTimeField(auto_now_add=True)),
                (
                    "pengaduan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riwayat_status",
                        to="pengaduan.pengaduan",
                    ),
                ),
                (
                    "petugas",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pengaduan.petugas",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pengaduan.statuslaporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tanggapan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi_tanggapan", models.TextField()),
                ("tanggal_tanggapan", models.DateTimeField(auto_now_add=True)),
                (
                    "pengaduan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanggapan",
                        to="pengaduan.pengaduan",
                    ),
                ),
                (
                    "petugas",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pengaduan.petugas",
                    ),
                ),
            ],
        ),
    ]
