# Generated by Django 5.2.3 on 2026-06-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("pengaduan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengaduan",
            name="masyarakat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pengaduan",
                to="accounts.masyarakat",
            ),
        ),
        migrations.RemoveField(
            model_name="petugas",
            name="user",
        ),
        migrations.AlterField(
            model_name="tanggapan",
            name="petugas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.petugas",
            ),
        ),
        migrations.AlterField(
            model_name="riwayatstatus",
            name="petugas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.petugas",
            ),
        ),
        migrations.DeleteModel(
            name="Masyarakat",
        ),
        migrations.DeleteModel(
            name="Petugas",
        ),
    ]
