# Generated by Django 5.2.3 on 2026-06-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengaduan", "0002_alter_pengaduan_masyarakat_remove_petugas_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengaduan",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="pengaduan.statuslaporan",
            ),
        ),
    ]
