# Generated by Django 5.2.3 on 2026-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengaduan", "0003_alter_pengaduan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengaduan",
            name="status",
            field=models.CharField(
                choices=[
                    ("MENUNGGU", "Menunggu"),
                    ("DIVERIFIKASI", "Diverifikasi"),
                    ("DIPROSES", "Diproses"),
                    ("SELESAI", "Selesai"),
                    ("DITOLAK", "Ditolak"),
                ],
                default="MENUNGGU",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="riwayatstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("MENUNGGU", "Menunggu"),
                    ("DIVERIFIKASI", "Diverifikasi"),
                    ("DIPROSES", "Diproses"),
                    ("SELESAI", "Selesai"),
                    ("DITOLAK", "Ditolak"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="StatusLaporan",
        ),
    ]
