# Generated by Django 5.2.3 on 2026-06-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pengaduan",
            "0004_alter_pengaduan_status_alter_riwayatstatus_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengaduan",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("LAINNYA", "Lainnya"),
                    ("ASPIRASI", "Aspirasi"),
                    ("PERMASALAHAN", "Permasalahan"),
                    ("PERINGATAN", "Peringatan"),
                    ("PERTANYAAN", "Pertanyaan"),
                ],
                default="LAINNYA",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="KategoriPengaduan",
        ),
    ]
