# Generated by Django 5.2.3 on 2026-06-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pengaduan", "0005_alter_pengaduan_kategori_delete_kategoripengaduan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pengaduan",
            options={"ordering": ["-tanggal_pengaduan"]},
        ),
    ]
